# Generated by Django 5.2.1 on 2025-05-25 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_productcatalog_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcatalog',
            name='original_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
