# Generated by Django 5.2.1 on 2025-05-26 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_recipe_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='isingredient',
            name='quantity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
