# Generated by Django 5.2.1 on 2025-05-31 07:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_isingredient_quantity'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='isingredient',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='isingredient',
            name='ingredientName',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='isingredient',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.productcatalog'),
        ),
        migrations.AlterUniqueTogether(
            name='isingredient',
            unique_together={('recipe', 'product', 'ingredientName')},
        ),
    ]
