# Generated by Django 5.2.1 on 2025-05-26 16:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_isingredient_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealplan',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='mealplan',
            name='day_of_week',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mealplan',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mealplan',
            name='plan_name',
            field=models.CharField(default='Kế hoạch bữa ăn', max_length=255),
        ),
        migrations.AddField(
            model_name='mealplan',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='mealplan',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
