# Generated by Django 5.2.1 on 2025-05-27 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_mealplan_recipe_alter_mealplan_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mealplan',
            name='recipe',
        ),
        migrations.AddField(
            model_name='mealplan',
            name='recipes',
            field=models.ManyToManyField(blank=True, to='api.recipe'),
        ),
    ]
