# Generated by Django 5.2.1 on 2025-05-31 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_isingredient_unique_together_and_more'),
        ('api', '0010_remove_mealplan_recipe_mealplan_recipes'),
    ]

    operations = [
    ]
