# Generated by Django 5.2.1 on 2025-06-01 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_user_options_user_address_user_bio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='product',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
