# Generated by Django 5.2.1 on 2025-06-03 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_ingredient_product_alter_ingredient_recipe_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AlterField(
            model_name='addtolist',
            name='quantity',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('housekeeper', 'Nội trợ'), ('member', 'Thành viên')], default='member', max_length=20),
        ),
    ]
