# Generated by Django 5.2.1 on 2025-06-09 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_passwordresetotp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mealplan',
            name='recipes',
        ),
        migrations.AlterField(
            model_name='shoppinglist',
            name='type',
            field=models.CharField(choices=[('day', 'Day'), ('week', 'Week')], max_length=10),
        ),
    ]
