# Generated by Django 5.2.1 on 2025-06-09 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_remove_mealplan_recipes_alter_shoppinglist_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealplan',
            name='recipes',
            field=models.ManyToManyField(blank=True, through='api.Have', to='api.recipe'),
        ),
    ]
